### ISSUE TITLE
Outdated dependencies?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/memestra-feedstock#8]
Over on https://github.com/conda-forge/jupyter-lsp-feedstock/pull/12 we're looking to make a "kitchen sink" pyls plugins package. On `pip check`, `pyls-memestra` fails, as `deprecated` is not installed. It looks like generally, the deps for `memestra` and `pyls-memestra` aren't particularly accurate anymore. Anyhow, going to pull it from this build, but please post an issue over there if the packages can back up to passing `pip check`... would PR, but have kind of a lot going on...

**Comment by marimeireles** [comment]
Thank you for letting me know @bollwyvl :)
I'll check this!

**Comment by marimeireles** [comment]
Hey @bollwyvl I think it's fixed now.
I think the problem was only on pyls-memestra, please let me know if I can help in any other way.
Thanks again for the ping :)

**Comment by bollwyvl** [comment]
Great, thanks it's up.

Opened https://github.com/conda-forge/pyls-memestra-feedstock/pull/10 to try and keep it from cropping up in the future.
